<?php

/**
 * @copyright Copyright &copy; Kartik Visweswaran, Krajee.com, 2013
 * @package yii2-datecontrol
 * @version 1.0.0
 */

namespace kartik\datecontrol;

use Yii;
use yii\base\InvalidConfigException;

/**
 * Date control module for Yii Framework 2.0
 *
 * @author Kartik Visweswaran <kartikv2@gmail.com>
 * @since 1.0
 */
class Module extends \yii\base\Module
{
    const FORMAT_DATE = 'date';
    const FORMAT_TIME = 'time';
    const FORMAT_DATETIME = 'datetime';

    /**
     * @var array the format settings for displaying each date attribute. An associative array that need to be setup as
     * $type => $format, where:
     * `$type`: integer, one of the FORMAT constants, and
     * `$format`: string, the PHP date/time format.
     * If this is not set, will automatically use the settings from Yii::$app->formatter based on the type setting in the
     * DateControl widget.
     */
    public $displaySettings = [];

    /**
     * @var array the format settings for saving each date attribute.  An associative array that need to be setup as
     * $type => $format, where:
     * `$type`: integer, one of the FORMAT constants, and
     * `$format`: string, the PHP date/time format. Set this to 'U' to save it in Unix timestamp.
     * @see `Module::initSettings()`
     */
    public $saveSettings = [];

    /**
     * @var bool whether to automatically use \kartik\widgets based on `$type`. Will use these widgets:
     * - \kartik\widgets\DatePicker for Module::FORMAT_DATE
     * - \kartik\widgets\TimePicker for Module::FORMAT_TIME
     * - \kartik\widgets\DateTimePicker for Module::FORMAT_DATETIME
     * If this is `true`, the `widgetSettings` will be autogenerated.
     * @see `Module::initSettings()`
     */
    public $autoWidget = true;

    /**
     * @var array the widget settings that will be used to render the date input. An associative array that need
     * to be setup as `$type` => `$settings`, where:
     * - `$type`: integer is one of the FORMAT constants, and
     * - `$settings`: array which consists of these keys:
     *    - `class`: string, the widget class name for the input widget that will render the date input.
     *    - `options`: array, the html attributes for the input widget
     * If `autoWidget` is true, this will be autogenerated.
     * @see `Module::initSettings()`
     */
    public $widgetSettings = [];

    /**
     * @var string the route/action to convert the date as per the `saveFormat` in DateControl widget.
     */
    public $convertAction = '/datecontrol/parse/convert';

    /**
     * @var array the the internalization configuration for this module
     */
    public $i18n = [];
    
    /**
     * Initializes the module
     */
    public function init()
    {
        $this->initI18N();
        $this->initSettings();
        parent::init();
    }


    public function initI18N()
    {
        Yii::setAlias('@datecontrol', dirname(__FILE__));
        if (empty($this->i18n)) {
            $this->i18n = [
                'class' => 'yii\i18n\PhpMessageSource',
                'basePath' => '@datecontrol/messages',
                'forceTranslation' => true
            ];
        }
        Yii::$app->i18n->translations['datecontrol'] = $this->i18n;
    }

    /**
     * Gets the default options for the `\kartik\widgets` based on `type`
     * @param $type
     * @param $format
     * @return array
     */
    public static function getWidgetOptions($type, $format) {
        $options = [];
        if (!empty($format) && $type !== self::FORMAT_TIME) {
            $options['convertFormat'] = true;
            $options['pluginOptions']['format'] = $format;
        } elseif (!empty($format) && $type === self::FORMAT_TIME) {
            $options['pluginOptions']['showSeconds'] = (strpos($format, 's') > 0) ? true : false;
            $options['pluginOptions']['showMeridian'] = (strpos($format, 'a') > 0 || strpos($format, 'A') > 0) ? true : false;
        }
        return $options;
    }

    /**
     * Initializes the default options for the `\kartik\widgets` based on `type`
     *
     * @param $type string the format type
     */
    protected function initWidgetOptions($type)
    {
        $attrib = $type . 'Format';
        $options = [];
        $format = isset(Yii::$app->formatter->$attrib) ? Yii::$app->formatter->$attrib : '';
        return static::getWidgetOptions($type, $format);
    }

    /**
     * Initializes module settings
     */
    public function initSettings()
    {
        $this->saveSettings += [
            self::FORMAT_DATE => 'Y-m-d',
            self::FORMAT_TIME => 'H:i:s',
            self::FORMAT_DATETIME => 'Y-m-d H:i:s',
        ];
        if ($this->autoWidget) {
            $this->widgetSettings = [
                self::FORMAT_DATE => ['class' => '\kartik\widgets\DatePicker'],
                self::FORMAT_TIME => ['class' => '\kartik\widgets\TimePicker'],
                self::FORMAT_DATETIME => ['class' => '\kartik\widgets\DateTimePicker'],
            ];
        }
        if (!empty($this->widgetSettings)) {
            foreach ($this->widgetSettings as $type => $setting) {
                if (empty($setting['class']) || !is_subclass_of($setting['class'], '\yii\widgets\InputWidget')) {
                    $message = empty($setting['class']) ? "No class was setup for the key '{$type}'." :
                        "The class '" . $setting['class'] . "' setup for key '{$type} is invalid or does not extend from '\\yii\\widgets\\InputWidget'";
                    throw new InvalidConfigException('Invalid widgetSettings in Date Control module config. ' . $message);
                }
                if ($this->autoWidget) {
                    $this->widgetSettings[$type]['options'] = $this->initWidgetOptions($type);
                }
            }
        }
    }
}